import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  varchar,
  pgEnum,
  uniqueIndex,
  index,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// ----------------------------------------------------------------------------
// Auth (managed by better-auth, schema is generated by CLI)
// Reference tables — do not rename. Run `npx @better-auth/cli generate`.
// ----------------------------------------------------------------------------

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  expiresAt: timestamp('expires_at'),
  password: text('password'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
})

// ----------------------------------------------------------------------------
// Salarasa domain tables
// ----------------------------------------------------------------------------

export const invitationStatusEnum = pgEnum('invitation_status', [
  'draft',
  'published',
  'archived',
])

export const eventTypeEnum = pgEnum('event_type', [
  'birthday',
  'wedding',
  'khitanan',
  'aqiqah',
  'syukuran',
  'seminar',
])

export const blockTypeEnum = pgEnum('block_type', [
  'splash_cover',
  'hero',
  'subject_biodata',
  'countdown_event',
  'dresscode',
  'gift',
  'rsvp',
  'guestbook',
  'thank_you',
  'footer',
])

export const rsvpAttendanceEnum = pgEnum('rsvp_attendance', [
  'hadir',
  'absen',
  'ragu',
])

export const themes = pgTable('themes', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  slug: varchar('slug', { length: 80 }).notNull().unique(),
  previewThumbnail: text('preview_thumbnail'),
  styleConfig: jsonb('style_config').$type<Record<string, any>>().notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const invitations = pgTable(
  'invitations',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    slug: varchar('slug', { length: 120 }).notNull(),
    eventType: eventTypeEnum('event_type').notNull().default('birthday'),
    themeId: integer('theme_id').references(() => themes.id),
    status: invitationStatusEnum('status').notNull().default('draft'),
    eventDate: timestamp('event_date'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    slugIdx: uniqueIndex('invitations_slug_idx').on(t.slug),
    userIdx: index('invitations_user_idx').on(t.userId),
  }),
)

export const invitationBlocks = pgTable(
  'invitation_blocks',
  {
    id: serial('id').primaryKey(),
    invitationId: text('invitation_id')
      .notNull()
      .references(() => invitations.id, { onDelete: 'cascade' }),
    blockType: blockTypeEnum('block_type').notNull(),
    config: jsonb('config').$type<Record<string, any>>().notNull().default({}),
    orderIndex: integer('order_index').notNull().default(0),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    invIdx: index('invitation_blocks_inv_idx').on(t.invitationId),
    orderIdx: index('invitation_blocks_order_idx').on(t.orderIndex),
  }),
)

export const greetings = pgTable(
  'greetings',
  {
    id: serial('id').primaryKey(),
    invitationId: text('invitation_id')
      .notNull()
      .references(() => invitations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    message: text('message').notNull(),
    attendance: rsvpAttendanceEnum('attendance'),
    isPublic: boolean('is_public').notNull().default(true),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    invIdx: index('greetings_inv_idx').on(t.invitationId),
  }),
)

export const rsvpResponses = pgTable(
  'rsvp_responses',
  {
    id: serial('id').primaryKey(),
    invitationId: text('invitation_id')
      .notNull()
      .references(() => invitations.id, { onDelete: 'cascade' }),
    guestName: text('guest_name').notNull(),
    jumlahTamu: integer('jumlah_tamu').notNull().default(1),
    attendance: rsvpAttendanceEnum('attendance'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    invIdx: index('rsvp_responses_inv_idx').on(t.invitationId),
  }),
)

// ----------------------------------------------------------------------------
// Relations
// ----------------------------------------------------------------------------

export const userRelations = relations(user, ({ many }) => ({
  invitations: many(invitations),
  sessions: many(session),
}))

export const invitationsRelations = relations(invitations, ({ one, many }) => ({
  user: one(user, { fields: [invitations.userId], references: [user.id] }),
  theme: one(themes, {
    fields: [invitations.themeId],
    references: [themes.id],
  }),
  blocks: many(invitationBlocks),
  greetings: many(greetings),
  rsvpResponses: many(rsvpResponses),
}))

export const invitationBlocksRelations = relations(
  invitationBlocks,
  ({ one }) => ({
    invitation: one(invitations, {
      fields: [invitationBlocks.invitationId],
      references: [invitations.id],
    }),
  }),
)

export const greetingsRelations = relations(greetings, ({ one }) => ({
  invitation: one(invitations, {
    fields: [greetings.invitationId],
    references: [invitations.id],
  }),
}))

export const rsvpResponsesRelations = relations(rsvpResponses, ({ one }) => ({
  invitation: one(invitations, {
    fields: [rsvpResponses.invitationId],
    references: [invitations.id],
  }),
}))

export const themesRelations = relations(themes, ({ many }) => ({
  invitations: many(invitations),
}))

// ----------------------------------------------------------------------------
// Block config schema (Zod) — validated in app layer, stored as JSONB
// ----------------------------------------------------------------------------

export type BlockType =
  | 'splash_cover'
  | 'hero'
  | 'subject_biodata'
  | 'countdown_event'
  | 'dresscode'
  | 'gift'
  | 'rsvp'
  | 'guestbook'
  | 'thank_you'
  | 'footer'

export type InvitationStatus = 'draft' | 'published' | 'archived'
export type EventType =
  'birthday' | 'wedding' | 'khitanan' | 'aqiqah' | 'syukuran' | 'seminar'
export type RsvpAttendance = 'hadir' | 'absen' | 'ragu'
